import type { Car } from './types';
export const MOCK_CARS: Car[] = [
  {
    id: 'WBA12345678901234',
    vin: 'WBA12345678901234',
    manufacturer: 'BMW',
    model: 'M3 Competition',
    year: 2023,
    inspectionValidUntil: new Date(new Date().setMonth(new Date().getMonth() + 10)).toISOString(),
    insuranceValidUntil: new Date(new Date().setMonth(new Date().getMonth() + 5)).toISOString(),
    cascoValidUntil: new Date(new Date().setMonth(new Date().getMonth() + 5)).toISOString(),
    fuelType: 'Gasoline',
    engineCapacity: 2993,
    enginePower: 510,
    enginePowerKW: 375,
    purchaseDate: new Date('2023-05-15').toISOString(),
    previousOwnersCount: 0,
    countryOfOrigin: 'Germany',
    countryOfManufacture: 'Germany',
    registrationDocumentNumber: 'XYZ12345',
    primaryPhotoUrl: 'https://images.unsplash.com/photo-1620439910134-88d7c45aef88?q=80&w=2070&auto=format&fit=crop',
    expenses: [],
    documents: [],
    photos: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'WDD2050401F123456',
    vin: 'WDD2050401F123456',
    manufacturer: 'Mercedes-Benz',
    model: 'C 300',
    year: 2022,
    inspectionValidUntil: new Date(new Date().setDate(new Date().getDate() + 20)).toISOString(), // Expires soon
    insuranceValidUntil: new Date(new Date().setMonth(new Date().getMonth() + 8)).toISOString(),
    fuelType: 'Gasoline',
    engineCapacity: 1991,
    enginePower: 258,
    enginePowerKW: 190,
    purchaseDate: new Date('2022-08-20').toISOString(),
    previousOwnersCount: 1,
    countryOfOrigin: 'Germany',
    countryOfManufacture: 'Germany',
    registrationDocumentNumber: 'ABC98765',
    primaryPhotoUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=2070&auto=format&fit=crop',
    expenses: [],
    documents: [],
    photos: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'WAUZZZFY123456789',
    vin: 'WAUZZZFY123456789',
    manufacturer: 'Audi',
    model: 'RS Q8',
    year: 2023,
    inspectionValidUntil: new Date(new Date().setMonth(new Date().getMonth() + 12)).toISOString(),
    insuranceValidUntil: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(), // Expired
    cascoValidUntil: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(), // Expired
    fuelType: 'Gasoline',
    engineCapacity: 3996,
    enginePower: 600,
    enginePowerKW: 441,
    purchaseDate: new Date('2023-01-10').toISOString(),
    previousOwnersCount: 0,
    countryOfOrigin: 'Germany',
    countryOfManufacture: 'Slovakia',
    registrationDocumentNumber: 'QRS67890',
    primaryPhotoUrl: 'https://images.unsplash.com/photo-1617469747579-9f249228f7ec?q=80&w=2070&auto=format&fit=crop',
    expenses: [],
    documents: [],
    photos: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'SALLMAM1234567890',
    vin: 'SALLMAM1234567890',
    manufacturer: 'Land Rover',
    model: 'Defender 110',
    year: 2021,
    inspectionValidUntil: new Date(new Date().setMonth(new Date().getMonth() + 6)).toISOString(),
    insuranceValidUntil: new Date(new Date().setMonth(new Date().getMonth() + 2)).toISOString(),
    fuelType: 'Diesel',
    engineCapacity: 2996,
    enginePower: 249,
    enginePowerKW: 183,
    purchaseDate: new Date('2021-11-05').toISOString(),
    previousOwnersCount: 1,
    countryOfOrigin: 'United Kingdom',
    countryOfManufacture: 'Slovakia',
    registrationDocumentNumber: 'DEF110UK',
    primaryPhotoUrl: 'https://images.unsplash.com/photo-1627457939551-52298a281d9f?q=80&w=2070&auto=format&fit=crop',
    expenses: [],
    documents: [],
    photos: [],
    createdAt: new Date().toISOString(),
  },
];